### ISSUE TITLE
S-2019-005-BCHN: Pre-Planning 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#44]
- [x] Application filed: Brief description of project, population of interest, nature of project challenge. (Application GitHub link)
[NE BRONX HEALTH STATUS INDICATORS 071219.docx](https://github.com/dlounsbu/PRIME_studios/files/3507001/NE.BRONX.HEALTH.STATUS.INDICATORS.071219.docx)
[Updated EDC Needs Section EL-2019-08-15.docx](https://github.com/dlounsbu/PRIME_studios/files/3507002/Updated.EDC.Needs.Section.EL-2019-08-15.docx)

- [x] Confirm SE Studio is correct approach for researcher's focus. (Need for studio GItHub link): We will apply a World Cafe format.

- [x] Identify facilitator based on relevant stakeholder characteristics/demographics: In this case, @dlounsbu will serve as facilitator. He is neutral to the topic and independent of BCHN.

- [x] Schedule planning meeting and share SE Studio FAQ: An initial meeting was held via Zoom on 2019-08-14 with BCHN staff.

**Comment by dlounsbu** [comment]
Here are my notes from today's call with Eleanor, Tashi, Paulette and others at BCHN.

[St Lukes Studio - Meeting Minutes - 2019-08-14.docx](https://github.com/dlounsbu/PRIME_studios/files/3503445/St.Lukes.Studio.-.Meeting.Minutes.-.2019-08-14.docx)

**Comment by dlounsbu** [comment]
@rachelduggan10 

I decided to delete the BCHN Wiki because Eleanor mentioned that she did not want others to read it. Also, the information it contained is the BCHN project, so nothing is lost.
