### ISSUE TITLE
S-2019-005-BCHN: Planning Meeting with Researcher/Research Team 

### ISSUE THREAD

**Issue by rachelduggan10** [dlounsbu/PRIME_studios#45]
- [x] PI, Navigator and facilitator meet together: Eleanor Larrier, Chief Executive Officer, BCHN, is the principal contact for this event. 

- [x] SE Studio process is explained/clarified.

- [x] SE Studio group rules are explained to researcher/research team: We agreed that a World Cafe format organized around the overarching theme of fostering access to community health services would be appropriate. 

- [x] Questions to be posed to Stakeholders are proposed/drafted (2-3 max, open-ended).

- [x] Characteristics of Stakeholder panel are defined. 

- [x] Stakeholder experts are coached on effective communication.

- [x] Study presentation template with guidelines for completion (provided to researcher).

- [x] Identify possible dates for SE Studio (3-4 dates): Tues, 2019-08-20 from 8:30am-11am. There will be a follow up World Cafe to be held the following week, in  the evening. Date for follow up World Cafe has not been decided.

**Comment by dlounsbu** [comment]
Venue for first World cafe: 
St. Luke's Catholic Church
623 E 138TH STREET, BRONX, NY

https://stlukebronx.org/

https://en.wikipedia.org/wiki/St._Luke%27s_Church_(Bronx,_New_York)
